// flow-typed signature: fe5ddba7dfdd70e174a4c64d9a7dd880
// flow-typed version: <<STUB>>/crypto_v^1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto' {
  declare module.exports: any;
}
